React capstone project - Metrics webapp
nilab-khwaja/metrics-webapp pull request #1
Opened 2023-10-10 10:22 UTC by nilab-khwaja

Select the makeup  API that I am  going to use.
Build files structure for React app.
Prepare routes and navigation in app.
 user can display a list of items and filter them. Data come from the API.
Create the tests for the application.
Style your components to match the design provided.
Deploy the project and test for final details.

2023-10-10 14:10 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @nilab-khwaja👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with SPA app. ✔️
- Highly organized code. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 14:10 UTC, thecodechaser commented on src/components/Makeup.jsx
> +      const brandName = makeup.brand ? makeup.brand.toLowerCase() : '';
- [ ] Please make sure to display two items in a row when on mobile screens, Currently it's showing one item per row. The provided design is for mobile screens so your application styles on mobile screens should match with the given design.

### Your design

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/43f210ef-95c9-4965-8d73-f48d25b34eae)

### Given design

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/8667d59d-2360-4561-83e4-a1690989e988)

2023-10-10 14:10 UTC, thecodechaser commented on src/components/MakupDetail.jsx
> +              <strong>Product type: </strong>
- [ ] Please also work on the details page styles, It should match with the given design and remove extra margins.

### Your design 

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/dd789d5d-b382-4215-83b6-830ed75ee8e9)

### Given design

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/15ab3fc6-05c3-40cf-aa66-4b89dc2dba68)

2023-10-10 14:10 UTC, thecodechaser commented on src/components/Makeup.jsx
> +      const productName = makeup.name ? makeup.name.toLowerCase() : '';
- [ ] Please make sure to use on of the below colors for the main theme color for your app as requested in the project requirements.

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/5d17f99d-45c0-4caa-8d21-a7263ff35f22)

2023-10-10 14:10 UTC, thecodechaser commented on src/__tests__/Makeup.test.js
> +  });
- [ ] The tests for `Makeup` and `MakeupDetail` are failing. Please make sure all tests are passing without any errors.

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/fc8a2911-9197-45e5-9a44-d260f5bd58fe)

2023-10-10 14:10 UTC, thecodechaser commented on README.md
> +- [Live Demo Link](https://beauty-494b.onrender.com)
- [ ] The live demo link is broken, Please make sure the live demo link works properly as requested in the project requirements.

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/224425db-1625-4441-86a9-e4da3178a766)

2023-10-10 14:10 UTC, thecodechaser commented on README.md
> +
- [ ] Good job on the presentation video but you missed showing some piece of code as requested in the project requirements. Please make sure to show some piece of code in the presentation video something you built that you are very proud of.

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/83803414/f23e4e2e-97ad-4d4f-97af-9b6b04a38426)

2023-10-10 14:10 UTC, thecodechaser commented on README.md
> +
- [ ] The issues page link is broken, Please make sure to fix this. It will make the README file more professional.

2023-10-10 14:11 UTC, thecodechaser commented
@nilab-khwaja You pushed some code after submitting the project for review. Please never push any changes after submitting the project for review until the PR receives a review.

2023-10-10 20:41 UTC, fobadara requested changes
Hi @nilab-khwaja, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 20:41 UTC, fobadara commented on src/components/MakupDetail.jsx
> +        <Link to="/"><button type="submit" className="goBack">Go Back</button></Link>
[REQUIRED] Kindly ensure that your back button is at the top left corner of your details page just like the template.

Your design
![image](https://github.com/nilab-khwaja/metrics-webapp/assets/62938735/51714803-f067-41e5-8835-c0b2a2556689)

Template
![image](https://github.com/nilab-khwaja/metrics-webapp/assets/62938735/8a227d41-a177-4774-b607-8874bf254504)

2023-10-10 20:41 UTC, fobadara commented on src/components/MakupDetail.jsx
> +          <li>
[REQUIRED] Please ensure that the edges and bottom of the details page don't have padding as shown in the image below. This will ensure that your design matches the template.

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/62938735/418902e0-7685-4e00-81ae-b2e057d5d31e)

2023-10-10 20:41 UTC, fobadara commented on README.md
> +- [Video Presentation Link](https://www.loom.com/share/9a2cacff8b824745869becd92456e3e7?sid=351b476b-78f7-4fdd-a380-2d856646ab6a)
[REQUIRED] You still didn't point out a piece of code that you find interesting as requested by the previous reviewer. Kindly do this.

2023-10-11 17:18 UTC, KDlamini commented on src/components/MakupDetail.jsx
> +        <Link to="/"><button type="submit" className="goBack">Go Back</button></Link>
Great job applying the required changes. You are almost close to completing all the requirements

As requested by the previous reviewer. Please place the go back button in the navbar:

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/38088818/652bf057-ba76-4ba3-b995-524e61e06527)

2023-10-11 17:19 UTC, KDlamini commented on src/components/MakupDetail.jsx
> +          <li>
Well resolved. Well done! ✔️ 

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/38088818/ce8fc177-e308-4e24-84f1-29949a9e72e5)

2023-10-11 17:28 UTC, KDlamini commented on README.md
> +- [Video Presentation Link](https://www.loom.com/share/9a2cacff8b824745869becd92456e3e7?sid=351b476b-78f7-4fdd-a380-2d856646ab6a)
Well resolved ✔️ 

✔️ The recorded video is presenting the features of the project. The maximum length of the video is 5 minutes.
✔️ The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
✔️ The video contains a demo of the project, highlighting all the project features.
✔️ The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2023-10-11 17:45 UTC, KDlamini requested changes
### Hi @nilab-khwaja 🙋‍♀️,  

You have done an incredible job implementing some of the changes requested by the previous reviewer. 👏🏾👏🏾👏🏾  
You have done an outstanding job so far, your application looks great. I know that the project requirements can be challenging. 
However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾 

## HIGHLIGHTS 🌟 

✔️ Great PR title and description
✔️ Events, fetch, and good state management with Redux
✔️ Good UI render and navigation for all pages
✔️ Well documented and professional README
✔️ Good API integration

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-11 17:45 UTC, KDlamini commented on README.md
> +  <img src="/src/assets/logo3.png" alt="Animation" width="150">
[OPTIONAL] If there's no logo for the application it is best to remove the image tag. It is unprofessional to leave broken images on the README.

2023-10-11 17:45 UTC, KDlamini commented on src/components/MakupDetail.jsx
> +        <Link to="/"><button type="submit" className="goBack">Go Back</button></Link>
You have done an incredible job creating a metrics web app using React and Redux. Thank you for showing dedication in applying Reacts concepts to render responsive UI 🎊 💯 

There's just one little detail to fix to proceed to the next project.
As requested by the previous reviewer. Please place the go back button in the navbar:

![image](https://github.com/nilab-khwaja/metrics-webapp/assets/38088818/652bf057-ba76-4ba3-b995-524e61e06527)

**Suggestion:**

I can see that you are rendering the same navbar for all your pages. 

- You can consider using conditional rendering to render different navbar content for the homepage and details page or render different navbars for each page. However, it is up to you how you want to implement this as long as you manage to include the back button in the navbar.


Overall, great work with the application 🚀

2023-10-11 20:35 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @nilab-khwaja, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights :green_circle: 

- Back button correctly displayed on the detail page as requested and design matches proposed design from the requirements :+1: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-10-12 09:37 UTC, merged